services:

  inventory-db:
    container_name: inventory-db
    image: postgres:latest
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./scripts/fix-partitions.sql:/docker-entrypoint-initdb.d/02-partitions.sql:ro
      - ./scripts/create-audit-log-indexes.sql:/docker-entrypoint-initdb.d/03-indexes.sql:ro
    restart: always

volumes:
  postgres_data:
