paths:
  /products:
    get:
      summary: 📋 Listar todos los productos
      description: |
        Obtiene una lista paginada de todos los productos en el inventario.
        
        ### Características
        - Paginación automática
        - Filtrado por estado
        - Ordenamiento por diferentes campos
        - Respuesta optimizada para grandes volúmenes
        
        ### Permisos Requeridos
        - **ADMIN**: Acceso completo
        - **USER**: Acceso de lectura
        - **VIEWER**: Solo lectura
      tags:
        - Products
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: Número de página (comienza en 1)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          example: 1
        - name: limit
          in: query
          description: Número de productos por página
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          example: 20
        - name: sort
          in: query
          description: Campo para ordenar (name, price, quantity, created_at)
          required: false
          schema:
            type: string
            enum: [name, price, quantity, created_at]
            default: created_at
          example: "name"
        - name: order
          in: query
          description: Orden de clasificación
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          example: "desc"
        - name: search
          in: query
          description: Término de búsqueda en nombre y descripción
          required: false
          schema:
            type: string
          example: "tornillo"
      responses:
        '200':
          description: ✅ Lista de productos obtenida exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListResponse'
              example:
                success: true
                message: "Productos obtenidos exitosamente"
                data:
                  products:
                    - id: 1
                      name: "Tornillo M8x20"
                      description: "Tornillo métrico 8mm x 20mm cabeza hexagonal"
                      price: 0.50
                      quantity: 1000
                      created_at: "2024-01-15T10:30:00.000Z"
                      updated_at: "2024-01-15T10:30:00.000Z"
                    - id: 2
                      name: "Tuerca M8"
                      description: "Tuerca métrica 8mm hexagonal"
                      price: 0.25
                      quantity: 2000
                      created_at: "2024-01-15T10:30:00.000Z"
                      updated_at: "2024-01-15T10:30:00.000Z"
                  pagination:
                    page: 1
                    limit: 20
                    total: 2
                    totalPages: 1
                    hasNext: false
                    hasPrev: false
                timestamp: "2024-01-15T10:30:00.000Z"
        '401':
          description: ❌ No autorizado - Token requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Token de autenticación requerido"
                error: "UNAUTHORIZED"
                timestamp: "2024-01-15T10:30:00.000Z"
        '403':
          description: ❌ Acceso denegado - Permisos insuficientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "No tienes permisos para acceder a este recurso"
                error: "FORBIDDEN"
                timestamp: "2024-01-15T10:30:00.000Z"

    post:
      summary: ➕ Crear nuevo producto
      description: |
        Crea un nuevo producto en el inventario.
        
        ### Validaciones
        - Nombre: Requerido, máximo 100 caracteres
        - Descripción: Opcional, máximo 500 caracteres
        - Precio: Requerido, mayor a 0
        - Cantidad: Requerido, mayor o igual a 0
        
        ### Permisos Requeridos
        - **ADMIN**: Crear productos
        - **USER**: Crear productos (limitado)
      tags:
        - Products
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
            example:
              name: "Tornillo M8x20"
              description: "Tornillo métrico 8mm x 20mm cabeza hexagonal"
              price: 0.50
              quantity: 1000
      responses:
        '201':
          description: ✅ Producto creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
              example:
                success: true
                message: "Producto creado exitosamente"
                data:
                  id: 1
                  name: "Tornillo M8x20"
                  description: "Tornillo métrico 8mm x 20mm cabeza hexagonal"
                  price: 0.50
                  quantity: 1000
                  created_at: "2024-01-15T10:30:00.000Z"
                  updated_at: "2024-01-15T10:30:00.000Z"
                timestamp: "2024-01-15T10:30:00.000Z"
        '400':
          description: ❌ Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
              example:
                success: false
                message: "Datos de entrada inválidos"
                error: "VALIDATION_ERROR"
                details:
                  - field: "name"
                    message: "El nombre es requerido"
                  - field: "price"
                    message: "El precio debe ser mayor a 0"
                timestamp: "2024-01-15T10:30:00.000Z"
        '401':
          description: ❌ No autorizado - Token requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: ❌ Acceso denegado - Permisos insuficientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /products/{id}:
    get:
      summary: 🔍 Obtener producto por ID
      description: |
        Obtiene los detalles completos de un producto específico por su ID.
        
        ### Información Incluida
        - Datos básicos del producto
        - Historial de modificaciones
        - Estado actual del inventario
        
        ### Permisos Requeridos
        - **ADMIN**: Acceso completo
        - **USER**: Acceso de lectura
        - **VIEWER**: Solo lectura
      tags:
        - Products
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID único del producto
          required: true
          schema:
            type: integer
            minimum: 1
          example: 1
      responses:
        '200':
          description: ✅ Producto encontrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
              example:
                success: true
                message: "Producto encontrado exitosamente"
                data:
                  id: 1
                  name: "Tornillo M8x20"
                  description: "Tornillo métrico 8mm x 20mm cabeza hexagonal"
                  price: 0.50
                  quantity: 1000
                  created_at: "2024-01-15T10:30:00.000Z"
                  updated_at: "2024-01-15T10:30:00.000Z"
                timestamp: "2024-01-15T10:30:00.000Z"
        '404':
          description: ❌ Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Producto con ID 1 no encontrado"
                error: "NOT_FOUND"
                timestamp: "2024-01-15T10:30:00.000Z"
        '401':
          description: ❌ No autorizado - Token requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse"

    put:
      summary: ✏️ Actualizar producto
      description: |
        Actualiza los datos de un producto existente.
        
        ### Características
        - Actualización parcial permitida
        - Validación de datos en tiempo real
        - Historial de cambios automático
        
        ### Permisos Requeridos
        - **ADMIN**: Actualizar cualquier producto
        - **USER**: Actualizar productos (limitado)
      tags:
        - Products
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID único del producto a actualizar
          required: true
          schema:
            type: integer
            minimum: 1
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
            example:
              name: "Tornillo M8x20 Mejorado"
              description: "Tornillo métrico 8mm x 20mm cabeza hexagonal con recubrimiento anticorrosivo"
              price: 0.75
              quantity: 1500
      responses:
        '200':
          description: ✅ Producto actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
              example:
                success: true
                message: "Producto actualizado exitosamente"
                data:
                  id: 1
                  name: "Tornillo M8x20 Mejorado"
                  description: "Tornillo métrico 8mm x 20mm cabeza hexagonal con recubrimiento anticorrosivo"
                  price: 0.75
                  quantity: 1500
                  created_at: "2024-01-15T10:30:00.000Z"
                  updated_at: "2024-01-15T11:45:00.000Z"
                timestamp: "2024-01-15T11:45:00.000Z"
        '400':
          description: ❌ Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: ❌ Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: ❌ No autorizado - Token requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse"
        '403':
          description: ❌ Acceso denegado - Permisos insuficientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse"

    delete:
      summary: 🗑️ Eliminar producto
      description: |
        Elimina permanentemente un producto del inventario.
        
        ⚠️ **ADVERTENCIA**: Esta acción es irreversible y eliminará permanentemente el producto.
        
        ### Permisos Requeridos
        - **ADMIN**: Eliminar cualquier producto
        - **USER**: No puede eliminar productos
      tags:
        - Products
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID único del producto a eliminar
          required: true
          schema:
            type: integer
            minimum: 1
          example: 1
      responses:
        '200':
          description: ✅ Producto eliminado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteResponse'
              example:
                success: true
                message: "Producto eliminado exitosamente"
                data:
                  id: 1
                  deleted_at: "2024-01-15T12:00:00.000Z"
                timestamp: "2024-01-15T12:00:00.000Z"
        '404':
          description: ❌ Producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Producto con ID 1 no encontrado"
                error: "NOT_FOUND"
                timestamp: "2024-01-15T12:00:00.000Z"
        '401':
          description: ❌ No autorizado - Token requerido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse"
        '403':
          description: ❌ Acceso denegado - Permisos insuficientes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse"